### ISSUE TITLE
hapi 13.x

### ISSUE THREAD

**Issue by jney** [ethanmick/airbrake-hapi#2]
`airbrake-hapi` officialy support 8.x
hapi 13.x doesn't look to be supported.
Any plan to support last version.

**Comment by ethanmick** [comment]
I no longer have access to my Airbrake account, but I can update to the newest Hapi API's and hope for the best. I'll leave it up to you and the community to test and report issues!

**Comment by jney** [comment]
thank you!

**Comment by ethanmick** [comment]
Alright, give `2.0.0` a try?

https://www.npmjs.com/package/airbrake-hapi

I didn't actually have to change the API, but I updated the package.json to use best practices for peer dependencies and it's more lenient on Hapi versions.
